### ISSUE TITLE
Immutable is undefined

### ISSUE THREAD

**Issue by MHerszak** [kraf/meteor-immutable#1]
Hi there,

I was just using your package and I am experiencing Immutable is 'undefined'. The error is actually: Cannot read property 'fromJS' of undefined. I am referencing it inside a package and I am also using it there.

```
class LoginStore extends EventEmitter {
    constructor() {
        super();
        let _this = this;
        _this._auth = Immutable.fromJS({});
    }
}
```

Any idea?

**Comment by kraf** [comment]
I'm afraid I haven't been using meteor for over a year now. I would guess that my package definition is out of date. This fork looks promising though: https://atmospherejs.com/dataflows/immutable
They also install a newer version of Immutable.js which had some breaking API changes. I would not recommend using Immutable 2.x anymore.
Would you mind closing the issue if the dataflows version works? I would then update the `Readme.md` to link to the working version.

**Comment by MHerszak** [comment]
I am using the Npm package and it works but thanks for your answer anyway!
